server:
  port: 8003

spring:
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_test
    username: root
    password: th1010110
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    name: localhost #主机名
  client:
    fetch-registry: false  #是否从注册中心获取信息
    register-with-eureka: false #单节点时不把自己注入注册中心
    service-url:
      defaultZone: http://${eureka.instance.name}:${server.port}/eureka/



