server:
  port: 7010

spring:
  application:
    name: goods-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: http://localhost:3306/spring_cloud
    username: root
    data-password: th1010110
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启mybatis驼峰

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ # eureka注册中心连接地址
  instance:
    lease-renewal-interval-in-seconds: 2 # 没隔两秒项服务器发送一次心跳，证明自己依然存活
    lease-expiration-duration-in-seconds: 10 # 告诉服务器，如果十秒之内没有发送心跳就代表我故障了，将我剔除掉
    prefer-ip-address: true # 告诉服务端，服务实例以IP作为链接，而不是以机器名
    instance-id: 34-springcloud-service-goods # 告诉服务器，服务实例名字



