server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: th1010110
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379


# 开启mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true





token:
  # token有效时间
  failTime: 10080

